# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addresspb/address.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='addresspb/address.proto',
  package='address',
  syntax='proto3',
  serialized_options=_b('Z\n/addresspb'),
  serialized_pb=_b('\n\x17\x61\x64\x64resspb/address.proto\x12\x07\x61\x64\x64ress\"\x1c\n\tAPRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"\xee\x02\n\nAPResponse\x12\r\n\x05house\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\x0c\n\x04near\x18\x03 \x01(\t\x12\x14\n\x0chouse_number\x18\x04 \x01(\t\x12\x0c\n\x04road\x18\x05 \x01(\t\x12\x0c\n\x04unit\x18\x06 \x01(\t\x12\r\n\x05level\x18\x07 \x01(\t\x12\x11\n\tstaircase\x18\x08 \x01(\t\x12\x10\n\x08\x65ntrance\x18\t \x01(\t\x12\x0e\n\x06po_box\x18\n \x01(\t\x12\x10\n\x08postcode\x18\x0b \x01(\t\x12\x0e\n\x06suburb\x18\x0c \x01(\t\x12\x15\n\rcity_district\x18\r \x01(\t\x12\x0c\n\x04\x63ity\x18\x0e \x01(\t\x12\x0e\n\x06island\x18\x0f \x01(\t\x12\x16\n\x0estate_district\x18\x10 \x01(\t\x12\r\n\x05state\x18\x11 \x01(\t\x12\x16\n\x0e\x63ountry_region\x18\x12 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x13 \x01(\t\x12\x14\n\x0cworld_region\x18\x14 \x01(\t2P\n\x13\x41\x64\x64ressParseService\x12\x39\n\x0c\x41\x64\x64ressParse\x12\x12.address.APRequest\x1a\x13.address.APResponse\"\x00\x42\x0cZ\n/addresspbb\x06proto3')
)




_APREQUEST = _descriptor.Descriptor(
  name='APRequest',
  full_name='address.APRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='address.APRequest.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=64,
)


_APRESPONSE = _descriptor.Descriptor(
  name='APResponse',
  full_name='address.APResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='house', full_name='address.APResponse.house', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='category', full_name='address.APResponse.category', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='near', full_name='address.APResponse.near', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='house_number', full_name='address.APResponse.house_number', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='road', full_name='address.APResponse.road', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unit', full_name='address.APResponse.unit', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level', full_name='address.APResponse.level', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='staircase', full_name='address.APResponse.staircase', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entrance', full_name='address.APResponse.entrance', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='po_box', full_name='address.APResponse.po_box', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='postcode', full_name='address.APResponse.postcode', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='suburb', full_name='address.APResponse.suburb', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='city_district', full_name='address.APResponse.city_district', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='city', full_name='address.APResponse.city', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='island', full_name='address.APResponse.island', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state_district', full_name='address.APResponse.state_district', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='address.APResponse.state', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='country_region', full_name='address.APResponse.country_region', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='country', full_name='address.APResponse.country', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='world_region', full_name='address.APResponse.world_region', index=19,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=433,
)

DESCRIPTOR.message_types_by_name['APRequest'] = _APREQUEST
DESCRIPTOR.message_types_by_name['APResponse'] = _APRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

APRequest = _reflection.GeneratedProtocolMessageType('APRequest', (_message.Message,), dict(
  DESCRIPTOR = _APREQUEST,
  __module__ = 'addresspb.address_pb2'
  # @@protoc_insertion_point(class_scope:address.APRequest)
  ))
_sym_db.RegisterMessage(APRequest)

APResponse = _reflection.GeneratedProtocolMessageType('APResponse', (_message.Message,), dict(
  DESCRIPTOR = _APRESPONSE,
  __module__ = 'addresspb.address_pb2'
  # @@protoc_insertion_point(class_scope:address.APResponse)
  ))
_sym_db.RegisterMessage(APResponse)


DESCRIPTOR._options = None

_ADDRESSPARSESERVICE = _descriptor.ServiceDescriptor(
  name='AddressParseService',
  full_name='address.AddressParseService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=435,
  serialized_end=515,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddressParse',
    full_name='address.AddressParseService.AddressParse',
    index=0,
    containing_service=None,
    input_type=_APREQUEST,
    output_type=_APRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADDRESSPARSESERVICE)

DESCRIPTOR.services_by_name['AddressParseService'] = _ADDRESSPARSESERVICE

# @@protoc_insertion_point(module_scope)
