// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: addresspb/address.proto

package addresspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type APRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *APRequest) Reset() {
	*x = APRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_addresspb_address_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APRequest) ProtoMessage() {}

func (x *APRequest) ProtoReflect() protoreflect.Message {
	mi := &file_addresspb_address_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APRequest.ProtoReflect.Descriptor instead.
func (*APRequest) Descriptor() ([]byte, []int) {
	return file_addresspb_address_proto_rawDescGZIP(), []int{0}
}

func (x *APRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type APResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	House         string `protobuf:"bytes,1,opt,name=house,proto3" json:"house,omitempty"`
	Category      string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Near          string `protobuf:"bytes,3,opt,name=near,proto3" json:"near,omitempty"`
	HouseNumber   string `protobuf:"bytes,4,opt,name=house_number,json=houseNumber,proto3" json:"house_number,omitempty"`
	Road          string `protobuf:"bytes,5,opt,name=road,proto3" json:"road,omitempty"`
	Unit          string `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	Level         string `protobuf:"bytes,7,opt,name=level,proto3" json:"level,omitempty"`
	Staircase     string `protobuf:"bytes,8,opt,name=staircase,proto3" json:"staircase,omitempty"`
	Entrance      string `protobuf:"bytes,9,opt,name=entrance,proto3" json:"entrance,omitempty"`
	PoBox         string `protobuf:"bytes,10,opt,name=po_box,json=poBox,proto3" json:"po_box,omitempty"`
	Postcode      string `protobuf:"bytes,11,opt,name=postcode,proto3" json:"postcode,omitempty"`
	Suburb        string `protobuf:"bytes,12,opt,name=suburb,proto3" json:"suburb,omitempty"`
	CityDistrict  string `protobuf:"bytes,13,opt,name=city_district,json=cityDistrict,proto3" json:"city_district,omitempty"`
	City          string `protobuf:"bytes,14,opt,name=city,proto3" json:"city,omitempty"`
	Island        string `protobuf:"bytes,15,opt,name=island,proto3" json:"island,omitempty"`
	StateDistrict string `protobuf:"bytes,16,opt,name=state_district,json=stateDistrict,proto3" json:"state_district,omitempty"`
	State         string `protobuf:"bytes,17,opt,name=state,proto3" json:"state,omitempty"`
	CountryRegion string `protobuf:"bytes,18,opt,name=country_region,json=countryRegion,proto3" json:"country_region,omitempty"`
	Country       string `protobuf:"bytes,19,opt,name=country,proto3" json:"country,omitempty"`
	WorldRegion   string `protobuf:"bytes,20,opt,name=world_region,json=worldRegion,proto3" json:"world_region,omitempty"`
}

func (x *APResponse) Reset() {
	*x = APResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_addresspb_address_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APResponse) ProtoMessage() {}

func (x *APResponse) ProtoReflect() protoreflect.Message {
	mi := &file_addresspb_address_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APResponse.ProtoReflect.Descriptor instead.
func (*APResponse) Descriptor() ([]byte, []int) {
	return file_addresspb_address_proto_rawDescGZIP(), []int{1}
}

func (x *APResponse) GetHouse() string {
	if x != nil {
		return x.House
	}
	return ""
}

func (x *APResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *APResponse) GetNear() string {
	if x != nil {
		return x.Near
	}
	return ""
}

func (x *APResponse) GetHouseNumber() string {
	if x != nil {
		return x.HouseNumber
	}
	return ""
}

func (x *APResponse) GetRoad() string {
	if x != nil {
		return x.Road
	}
	return ""
}

func (x *APResponse) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *APResponse) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *APResponse) GetStaircase() string {
	if x != nil {
		return x.Staircase
	}
	return ""
}

func (x *APResponse) GetEntrance() string {
	if x != nil {
		return x.Entrance
	}
	return ""
}

func (x *APResponse) GetPoBox() string {
	if x != nil {
		return x.PoBox
	}
	return ""
}

func (x *APResponse) GetPostcode() string {
	if x != nil {
		return x.Postcode
	}
	return ""
}

func (x *APResponse) GetSuburb() string {
	if x != nil {
		return x.Suburb
	}
	return ""
}

func (x *APResponse) GetCityDistrict() string {
	if x != nil {
		return x.CityDistrict
	}
	return ""
}

func (x *APResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *APResponse) GetIsland() string {
	if x != nil {
		return x.Island
	}
	return ""
}

func (x *APResponse) GetStateDistrict() string {
	if x != nil {
		return x.StateDistrict
	}
	return ""
}

func (x *APResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *APResponse) GetCountryRegion() string {
	if x != nil {
		return x.CountryRegion
	}
	return ""
}

func (x *APResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *APResponse) GetWorldRegion() string {
	if x != nil {
		return x.WorldRegion
	}
	return ""
}

var File_addresspb_address_proto protoreflect.FileDescriptor

var file_addresspb_address_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x70, 0x62, 0x2f, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x22, 0x25, 0x0a, 0x09, 0x41, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0xaa, 0x04, 0x0a, 0x0a, 0x41, 0x50,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x65,
	0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x65, 0x61, 0x72, 0x12, 0x21,
	0x0a, 0x0c, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x61, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x72, 0x6f, 0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x69, 0x72, 0x63, 0x61, 0x73, 0x65, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x69, 0x72, 0x63, 0x61, 0x73, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x70, 0x6f, 0x5f,
	0x62, 0x6f, 0x78, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x6f, 0x42, 0x6f, 0x78,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x75, 0x62, 0x75, 0x72, 0x62, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x75,
	0x62, 0x75, 0x72, 0x62, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x64, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x63, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x69, 0x74,
	0x79, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74,
	0x79, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x69, 0x73, 0x6c, 0x61, 0x6e, 0x64, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69,
	0x73, 0x6c, 0x61, 0x6e, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x64,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x72, 0x65,
	0x67, 0x69, 0x6f, 0x6e, 0x18, 0x12, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x18, 0x13, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x5f, 0x72, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x77, 0x6f, 0x72, 0x6c, 0x64,
	0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x32, 0x50, 0x0a, 0x13, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x50, 0x61, 0x72, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a,
	0x0c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x50, 0x61, 0x72, 0x73, 0x65, 0x12, 0x12, 0x2e,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x41, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x13, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x41, 0x50, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2f, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_addresspb_address_proto_rawDescOnce sync.Once
	file_addresspb_address_proto_rawDescData = file_addresspb_address_proto_rawDesc
)

func file_addresspb_address_proto_rawDescGZIP() []byte {
	file_addresspb_address_proto_rawDescOnce.Do(func() {
		file_addresspb_address_proto_rawDescData = protoimpl.X.CompressGZIP(file_addresspb_address_proto_rawDescData)
	})
	return file_addresspb_address_proto_rawDescData
}

var file_addresspb_address_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_addresspb_address_proto_goTypes = []interface{}{
	(*APRequest)(nil),  // 0: address.APRequest
	(*APResponse)(nil), // 1: address.APResponse
}
var file_addresspb_address_proto_depIdxs = []int32{
	0, // 0: address.AddressParseService.AddressParse:input_type -> address.APRequest
	1, // 1: address.AddressParseService.AddressParse:output_type -> address.APResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_addresspb_address_proto_init() }
func file_addresspb_address_proto_init() {
	if File_addresspb_address_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_addresspb_address_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_addresspb_address_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_addresspb_address_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_addresspb_address_proto_goTypes,
		DependencyIndexes: file_addresspb_address_proto_depIdxs,
		MessageInfos:      file_addresspb_address_proto_msgTypes,
	}.Build()
	File_addresspb_address_proto = out.File
	file_addresspb_address_proto_rawDesc = nil
	file_addresspb_address_proto_goTypes = nil
	file_addresspb_address_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AddressParseServiceClient is the client API for AddressParseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AddressParseServiceClient interface {
	AddressParse(ctx context.Context, in *APRequest, opts ...grpc.CallOption) (*APResponse, error)
}

type addressParseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAddressParseServiceClient(cc grpc.ClientConnInterface) AddressParseServiceClient {
	return &addressParseServiceClient{cc}
}

func (c *addressParseServiceClient) AddressParse(ctx context.Context, in *APRequest, opts ...grpc.CallOption) (*APResponse, error) {
	out := new(APResponse)
	err := c.cc.Invoke(ctx, "/address.AddressParseService/AddressParse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddressParseServiceServer is the server API for AddressParseService service.
type AddressParseServiceServer interface {
	AddressParse(context.Context, *APRequest) (*APResponse, error)
}

// UnimplementedAddressParseServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAddressParseServiceServer struct {
}

func (*UnimplementedAddressParseServiceServer) AddressParse(context.Context, *APRequest) (*APResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddressParse not implemented")
}

func RegisterAddressParseServiceServer(s *grpc.Server, srv AddressParseServiceServer) {
	s.RegisterService(&_AddressParseService_serviceDesc, srv)
}

func _AddressParseService_AddressParse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressParseServiceServer).AddressParse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/address.AddressParseService/AddressParse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressParseServiceServer).AddressParse(ctx, req.(*APRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AddressParseService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "address.AddressParseService",
	HandlerType: (*AddressParseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddressParse",
			Handler:    _AddressParseService_AddressParse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "addresspb/address.proto",
}
